version: 2

build:
  os: ubuntu-22.04
  tools:
    # TODO: Support Python 3.11.
    python: "3.10"

sphinx:
  configuration: manual/conf.py

python:
  install:
  - requirements: manual/requirements.txt
