# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('..'))

from scenedetect import __version__ as scenedetect_version

# -- Project information -----------------------------------------------------

project = 'PySceneDetect'
copyright = '2014-2024, Brandon Castellano'
author = 'Brandon Castellano'

# The short X.Y version
version = scenedetect_version
# The full version, including alpha/beta/rc tags
release = scenedetect_version

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.napoleon',
    'sphinx.ext.autodoc',
]

autoclass_content = "both"
autodoc_member_order = "groupwise"
autodoc_typehints = 'description'
autodoc_typehints_format = 'short'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The root toctree document.
root_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['pyscenedetect.css']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'PySceneDetectdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
                   # The paper size ('letterpaper' or 'a4paper').
                   #
                   # 'papersize': 'letterpaper',

                   # The font size ('10pt', '11pt' or '12pt').
                   #
                   # 'pointsize': '10pt',

                   # Additional stuff for the LaTeX preamble.
                   #
                   # 'preamble': '',

                   # Latex figure (float) alignment
                   #
                   # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (root_doc, 'PySceneDetect.tex', 'PySceneDetect Documentation', 'Brandon Castellano', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(root_doc, 'pyscenedetect', 'PySceneDetect Documentation', [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (root_doc, 'PySceneDetect', 'PySceneDetect Documentation', author, 'PySceneDetect',
     'Python API and `scenedetect` command reference.', 'Miscellaneous'),
]

# -- Theme -------------------------------------------------

# TODO: Consider switching to sphinx_material.

html_theme = 'alabaster'
html_theme_options = {
    'sidebar_width': '235px',
    'description': 'Version: [%s]' % (release),
    'show_relbar_bottom': True,
    'show_relbar_top': False,
    'github_user': 'Breakthrough',
    'github_repo': 'PySceneDetect',
    'github_type': 'star',
    'tip_bg': '#f0f6fa',
    'tip_border': '#c2dcf2',
    'hint_bg': '#f0faf0',
    'hint_border': '#d3ebdc',
    'warn_bg': '#f5ebd0',
    'warn_border': '#f2caa2',
    'attention_bg': '#f5dcdc',
    'attention_border': '#ffaaaa',
    'logo': 'pyscenedetect_logo.png',
    'logo_name': False,
}
