
name: Linux Build

on: [pull_request, push]

jobs:
  build:

    runs-on: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # TODO: `setuptools` is pinned for the Python 3.7 builder and can be unpinned when removed.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build wheel virtualenv setuptools==62.3.4
          pip install av==9.2 opencv-python-headless==4.6.0.66 --only-binary :all:
          pip install -r requirements_headless.txt
      - name: Checkout test resources
        run: |
          git fetch --depth=1 https://github.com/Breakthrough/PySceneDetect.git refs/heads/resources:refs/remotes/origin/resources
      - name: Build module
        run: |
          python -m build
      - name: Run unit tests
        run: |
          python -m pytest tests/
