# Ensure the Windows distribution works without any pre-installed dependencies.
name: Test Windows Distribution

on:
  workflow_run:
    workflows: [Windows Distribution]
    types:
      - completed

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: resources

      - uses: actions/download-artifact@v3
        with:
          name: PySceneDetect-win64_portable
          path: build

      - name: Test
        run: |
          ./build/scenedetect version
          ./build/scenedetect -i tests/resources/goldeneye.mp4 -b opencv detect-content time --end 00:10:00
          ./build/scenedetect -i tests/resources/goldeneye.mp4 -b pyav detect-content time --end 00:10:00
          ./build/scenedetect -i tests/resources/goldeneye.mp4 detect-content time --end 00:10:00 split-video
          ./build/scenedetect -i tests/resources/goldeneye.mp4 detect-content time --end 00:10:00 split-video -m
